[bybit]
base_url_trading = "https://public.bybit.com/trading/"
api_key = ""
api_secret = ""

[telegram]
telegram_token = ""
telegram_chenal_id = ""
telegram_chat_id = ""

[base_settings]
base_symbol = "DOGE/USDT"
base_days_deph = 30
